version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Allow updates for TS
      - dependency-name: "typescript"
    versioning-strategy: increase

