version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Allow updates for TS (except for patches, since they are not expected to introduce breaking changes)
    allow:
      - dependency-name: "typescript"
    versioning-strategy: increase

